steps:
  # 1. Construir la imagen de Docker usando el Dockerfile
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      
      # --- ¡LÍNEA NUEVA AÑADIDA! ---
      # Pasa la variable _VITE_API_URL al Dockerfile como un argumento de build
      - '--build-arg'
      - 'VITE_API_URL=${_VITE_API_URL}'
      
      - '.'

  # 2. Subir la imagen a Artifact Registry (recomendado sobre GCR)
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

  # 3. Desplegar la imagen en Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}' # El nombre de tu servicio en Cloud Run
      - '--image'
      - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # ¡Importante para que el sitio sea público!

# Guardamos la imagen en Artifact Registry
images:
  - '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/${_SERVICE_NAME}:${COMMIT_SHA}'

# Variables de sustitución.
# Puedes definirlas aquí o en la configuración del Trigger.
substitutions:
  _SERVICE_NAME: 'sumadots-frontend'
  _REGION: 'europe-west1' 
  _REPO_NAME: 'sumadots-frontend' 
  
  # --- ¡LÍNEA NUEVA AÑADIDA! ---
  # Define la variable con la URL de tu backend
  _VITE_API_URL: 'https://sumadots-website-submitform-56755484181.europe-west1.run.app'